# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'First ios-node Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftKeychainWrapper', '~> 4.0'
  # Pods for First ios-node Project

end
